version: '3.4'

networks:
  lbrynet:
    external: true

services:
#############
## Lbrycrd ##
#############
  lbrycrd:
    build: .
    restart: always
    networks:
      lbrynet
        ipv4_address: 10.10.0.1
    labels:
      - "traefik.expose=false"
    expose:
      - 9245
      - 9246
    ## host volumes for persistent data such as wallet private keys.
    volumes:
      - ./data/:/data
      - ./config:/etc/lbrycrdd
