#Debug mode outputs specific information to the console
DEFAULT-debugmode=false

#LBRYcrd URL is required for chainquery to query the blockchain
DEFAULT-lbrycrdurl="rpc://lbryrpc:changeme@10.10.0.3:9245"

#MySQL DSN is required for chainquery to store information.
DEFAULT-mysqldsn="changeme:changeme@tcp(10.10.0.10:3306)/chainquery"

#API MySQL DSN is required for chainquery to expose a SQL query service
DEFAULT-apimysqldsn="changeme:changeme@tcp(0.0.0.0:3306)/chainquery"

#API Host and Port is required for the API Server to bind and listen on.
DEFAULT-apihostport="0.0.0.0:6300"

#Profile mode enables and disables the reporting of a profile for chainquery
#DEFAULT-profilemode=false

#Daemon mode tells chainquery how hard it should work catch up processing the blockchain
#DEFAULT-deamonmode=0 #BeastMode it continuously process block after block until caughtup.
#daemonmode=1 #SlowAndSteadyMode it will process block with a frequency of 1 block every 100ms
#daemonmode=2 #DelayMode it will process a block with a configured delay frequency (set via 'processingdelay')
#daemonmode=3 #DaemonMode it will process a block every iteration of the daemon.

#Default client timeout is for communication with the api of chainquery
#DEFAULT-defaultclienttimeout=20 #Measured in seconds

#Processing delay is used to determine how frequently chainquery should process a block
# It is only used if Daemon mode is set to delay mode
#DEFAULT-processingdelay=100 #Measured in milliseconds

#Daemon delay is the frequency at which chainquery checks for work to do.
#DEFAULT-daemondelay=1 #Measured in seconds

#Profiling options - will output the time take for certain opertions related to the below category
#DEFAULT-daemonprofile=false
#DEFAULT-lbrycrdprofile=false
#DEFAULT-mysqlprofile=false

#Slack Hook URL allows slack integration. All logging info level and above is posted to a slack channel.
#DEFAULT-slackhookurl=[unset]

#Slack Channel is the channel that you want the messages to appear. Works together with the hook url.
#DEFAULT-slackchannel=[unset]

#Slack Log Level tells chainquery what level of logging will be sent to the slack channel. It will log all levels below
# it as well. Panic=0,Fatal=1,Error=2,Warning=3,Info=4,Debug=5
#DEFAULT-slackloglevel=0

#The command that should be executed to trigger a self update of the software. For linux, for example, `<yourscript>.sh`
#DEFAULT-autoupdatecommand=[unset]

#Twilio service of chainquery to send specifically important information to key users of the Chainquery install.
#DEFAULT-twiliosid=""
#DEFAULT-twilioauthtoken=""
#DEFAULT-smsrecipients=["",""]
#DEFAULT-smsfromphonenumber=""
