version: '3.4'

networks:
  lbrynet:
    external: true

services:
################
## Chainquery ##
################
  chainquery:
    build: .
    restart: always
    networks:
      lbrynet:
        ipv4_address: 10.10.0.2
    labels:
      - "traefik.expose=false"
    expose:
      - ####
    ## host volumes for persistent data such as wallet private keys.
    volumes:
      - ./data/:/data
