version: '3.4'

networks:
  traefik:
    external: true

services:
#############
## Lbrynet ##
#############
  traefik:
    build: .
    restart: always
    networks:
      traefik:
        ipv4_address: 10.5.1.4
    labels:
      - "traefik.expose=false"
    ports:
      - 4444:4444
      - 50001:50001
    ## host volumes for persistent data such as wallet private keys.
    volumes:
      - ./data/:/data
